### PR TITLE
feat: add spot_trade circuit

### PR DESCRIPTION
**Pull request by HAOYUatHZ**

### CODE REVIEW

**Comment by lispc** [comment]
Will it be better to use `quote` / `base` rather than 2to1/1to2 ? 
Can order1 order2 be exchanged? Is it a good idea to treat order1 as maker and treat order2 as taker? Or one buy one sell?

**Comment by HAOYUatHZ** [comment]
> Can order1 order2 be exchanged? Is it a good idea to treat order1 as maker and treat order2 as taker?

If we want to have different fee rates for maker and taker, then it's necessary to tell who's then maker and then who's taker.

It's true that we can support exchanging order1 & order2, and applying maker fee to the earlier tx, and taker fee to the latter tx.

However, this introduces additional conditional branches. i.e., 
```
if tx_1.timstamp >= tx_2.timstamp then
  tx_1.fee = takerfee
  tx_2.fee = makerfee
else
  tx_1.fee = makerfee
  tx_2.fee = takerfee
```

Without loss of generality, we just specify tx1 as maker and tx2 as taker.
we now only need to constrain tx_1.timstamp >= tx_2.timstamp, and use `tx_1.fee = takerfee; tx_2.fee = makerfee` directly.

**Comment by HAOYUatHZ** [comment]
The role (taker/maker) of an order can be different in different trades (deals).
Say order1.timestamp > order2.timestamp > order3.timestamp;
order1 matches order2 and order1 gets filled, but order2 haven't been filled yet. order2 is the taker here.
then order2 matches order3, and order2 becomes the maker.

**Comment by HAOYUatHZ** [comment]
> Or buy vs sell?

An order is both buying and selling at the same time. Indeed you could bind it to a market_symbol (quote/base), then you could specify the side (buy/sell), but I think this introduces more checks (which means more complexity and less flexibility) in smart_contract and DEX backend.

**Comment by HAOYUatHZ** [comment]
> Will it be better to use quote / base rather than 2to1/1to2 ?

It really depends. If we keep using order1 as maker and order2 as taker, then amount_2to1 may not be quote_amount, and may not be base_amount either.

As explained before, indeed we could use quote_base symbol & sides & quote_base amount. Then we can use quote_base amount instead of amount_2to1/1to2. And taker/maker are not always order1/order2 anymore.

But for now I still prefer use order1 as maker and order2 as taker, because we can reduce conditional branches in the circuit. In this way we will have to use amount_2to1/1to2 instead of quote/base_amount.

**Review by lispc — APPROVED** [review]

**Pull request merged**
